### ISSUE TITLE
Contribuciones Rocío Cenador

### ISSUE THREAD

**Issue by Rcenador** [Arquisoft/radarin_es3b#167]
- [ ] Mantenimiento de la calidad del código: [code quality](https://app.codacy.com/gh/Arquisoft/radarin_es3b/dashboard?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/radarin_es3b&utm_campaign=Badge_Grade) (- 59% issues)
- [ ] Investigación temas relacionados con Solid (#93, #57, #7)
- [ ] Pruebas no incluídas en el release que forman parte de investigación:
- inrupt/generator_solid_react , [Solid React Application Generator](https://github.com/inrupt/generator-solid-react)
- Notificaciones "no push" con la librería [react_notifications_components](https://www.npmjs.com/package/react-notifications-component)  (#121) (commit: 09f5dea9e0383cce07cc5bc4473a873960336e04)
- [ ] Display lista de amigos por sus nombres (https://github.com/Arquisoft/faq/issues/8)
- [ ] Creación de Actas (#88)
- [ ] Solución bug issue con jest.config (#154)
- [ ] Solución bug componente geoLocation y tests (#68)
- [ ] Actualizar documentación (#127, #48, #37, #36, #4)
- [ ] Monitorización de la aplicación: first-release-dashboard.json (#134) (commit: a62d11bd728f4583e7859d28a4141c533462fabb)
- [ ] Otros issues:  #122, #59
- [ ] GUI vista Ayuda (commit: 8df874e888bd4adc78e4f7769ec9bbc1e5422f77)
- [ ] GUI vista Admin con Luis Lomba Martínez
- [ ] Estilo de la vista Amigos (commit: 40da8e162f5ae5728ccd178d5f4d7f62b2beeed5)
