### ISSUE TITLE
Contribuciones Enrique Vera

### ISSUE THREAD

**Issue by UO246711** [Arquisoft/radarin_es3b#168]
- [ ] Actualización de los apartados 3 y 4 de la documentación: #126
- [ ] Conexión de todos las partes del prototitpo en uno compacto #131
- [ ] Limpieza de tests y y areglo de fallos que impedian desplegar en heroku en el periodo del prototipo , (commits del 5,8 y 9 de Marzo.)
- [ ] Despliegue correcto del mapa en Heroku #87
- [ ]  Creación de Actas #88
- [ ] Creación de todos los metodos y entidades de restapi necesarios para la aplicación (guardar,borrar leer y actualizar   localizaciones...): #56, #94, #130
- [ ] Creación del mapa y geolocalización del usuario, asi como de los componentes para su activación y desactivación :#56, #82
- [ ] Hooks para poder leer como strings "limpois" el WebID del usuario y sus amigos y poder pasarselo a los componentes del mapa. #130
- [ ] Mapa en tiempo real, actualizando las localizaciones del usuario y sus amigos constamente en refrescos del mapa de 5 segundos. #135, #133
- [ ] Sincronización de las notificaciones con la aparición de amigos en el mapa junto @Lu-UniOvi , ayuda con el #129
- [ ] Solución de incompatibilidad de los tests con mapbox https://github.com/Arquisoft/radarin_es3b/commit/fdebef7ad19617f8976ee87698925850fdcf8623

**Comment by UO246711** [comment]
Duplicado por error, cerrado
