### ISSUE TITLE
Contribuciones Rocío Cenador  

### ISSUE THREAD

**Issue by Rcenador** [Arquisoft/radarin_es3b#259]
- [ ] Desarrollo de test unitarios y test de aceptación #222 (hasta 48% cobertura) [codeCov](https://codecov.io/gh/Arquisoft/radarin_es3b)  
- [ ] Tests de la restapi  
- [ ] Creación de anexo para la documentación  
- [ ] Mantenimiento de la calidad del código: [code quality](https://app.codacy.com/gh/Arquisoft/radarin_es3b/dashboard?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/radarin_es3b&utm_campaign=Badge_Grade)
- [ ] Investigación temas relacionados con Solid (#93, #57, #7)
- [ ] Pruebas no incluídas en el release que forman parte de investigación:
- inrupt/generator_solid_react , [Solid React Application Generator](https://github.com/inrupt/generator-solid-react)
- Notificaciones "no push" con la librería [react_notifications_components](https://www.npmjs.com/package/react-notifications-component)  (#121) (commit: 09f5dea9e0383cce07cc5bc4473a873960336e04)
- Intentos de simular sesión para los tests con [@inrupt/solid-client-authn](https://github.com/inrupt/solid-client-authn-js), [solid-auth-client](https://github.com/solid/solid-auth-client), [solid-auth-fetcher](https://github.com/solid/solid-auth-fetcher)
- [ ] Display lista de amigos por sus nombres (https://github.com/Arquisoft/faq/issues/8)
- [ ] Creación de Actas (#88)
- [ ] Solución bug issue con jest.config (#154)
- [ ] Solución bug componente geoLocation y tests (#68)
- [ ] Actualizar documentación (#127, #48, #37, #36, #4)
- [ ] Monitorización de la aplicación: first-release-dashboard.json (#134) (commit: a62d11bd728f4583e7859d28a4141c533462fabb)
- [ ] Otros issues:  #122, #59
- [ ] GUI vista Ayuda (commit: 8df874e888bd4adc78e4f7769ec9bbc1e5422f77) para primer release
- [ ] GUI vista Admin con Luis Lomba Martínez para primer release
- [ ] Estilo de la vista Amigos (commit: 40da8e162f5ae5728ccd178d5f4d7f62b2beeed5)  
- [ ] Contribuciones anteriores: #167, #25
